### ISSUE TITLE
TechReborn energy no longer transferring

### ISSUE THREAD

**Issue by Starjumper2821** [GabrielOlvH/Industrial-Revolution#124]
Not quite sure when it happened, but after installing version 1.8.0 TechReborn energy no longer fills IR machines. Since this did allow some bypassing of of the tech tree I won't call it a bug, but it is somewhat annoying. Is it possible to regain this feature?

Reason:
TechReborn has a fusion reactor and I don't have space to cross over 3 different cables in my base.

**Comment by GabrielOlvH** [comment]
IR now uses a different, better energy api which as a side effect, TR's cables can no longer interact with IR's machines. You can still use IR cables to power everything (they work with TR machines) but this incompatibility will exist until this (or similar) energy api becomes standard because the old one was not enough.
