### ISSUE TITLE
iron dust not smelting

### ISSUE THREAD

**Issue by peanutinky** [GabrielOlvH/Industrial-Revolution#14]
iron dust don't smelt in eletric furnace or vanilla furnace

**Comment by GabrielOlvH** [comment]
Sorry about that, another missing recipe. Since Cotton Resources was removed I need to add these recipes myself and I forgot a few. The next update with it fixed should come out sometime this week. A quick solution, if you want, is add another mod that adds this recipe (TechReborn or even Cotton Resources). I'm very sorry.

**Comment by Linguardium** [comment]
you could also just throw in a datapack. you cna use https://crafting.thedestruc7i0n.ca/ to make the recipe and datapack for the regular smelter

**Comment by GabrielOlvH** [comment]
Fixed as of 1.2.0-BETA which you can download [here](https://www.curseforge.com/minecraft/mc-mods/industrial-revolution/files/3012763)
