### ISSUE TITLE
[BUG] Your Mod Broken with KubeJS

### ISSUE THREAD

**Issue by ModernGamingWorld** [GabrielOlvH/Industrial-Revolution#174]
**Description:**
- Give a detailed explanation of the issue
-  Your mod is causing Kubejs Fabric to throw a ton of errors

**Steps to Reproduce:**
- Steps to reproduce this behaviour
-  Install KubeJs in my custom Fabric pack and boom tons of spam

**Technical Information:**
 - Minecraft: 1.16.5
 - Fabric API: 0.34.2+1.16
 - Industrial Revolution: 1.9.10-beta
 - Modpack: Fabric Exploration, note the current release wont have the issue as my next release will have kubejs installed

**Logs:**
- Use a paste service, do not paste the logs directly here.

**Details:**
Extra information that might be helpful like screenshots or technical information about your computer.

![2021-05-15_21 02 09](https://user-images.githubusercontent.com/75923060/118383644-6a356100-b5c5-11eb-9aa3-ac16127390da.png)

**Comment by MaxNeedsSnacks** [comment]
Note: We updated KubeJS and removed some deprecated wrappers recently, please use „Platform“ instead of „mod“ for your mod integration (see PlatformWrapper)

We didn’t expect mods to actually be including scripts in their default datapacks, so that’s why we pushed that breaking change

Also as a future note — you should probably add a better indicator for the fact that these scripts are loaded through IR, for example by changing the datapack namespace to something like „ir_compat“
