### ISSUE TITLE
[BUG] Crash with Storage Cabinets

### ISSUE THREAD

**Issue by red2blue** [GabrielOlvH/Industrial-Revolution#342]
Player connected Storage Cabinet and Indrev together. Apparently indrev was trying to push multiple different items into storage cabinet, causing a crash. 

**crash log**: [](https://pastebin.com/myhzXQA0)

**steps to reproduce**

- hook a cabinet up to an industrial revolution item pipe without setting a whitelist, it tries to send the everything on the network into the cabinet even though it only accepts one type of item, which crashes the serv

reported on storage cabinet github as well https://github.com/AshIndigo/Storage_Cabinet/issues/17

**Comment by GabrielOlvH** [comment]
Thanks for reporting, but this actually seems to be a performance issue. 
Storage Cabinets seem to do some logic to find every tag an item has which is slow. To be clear, it needs to iterate through every tag and then check if that tag contains the item, then IR tries to insert multiple items per tick, causing the watchdog to kill the server. There are a possibility for optimization I see which I'll bring up in your report on their issue tracker.
I'll close this since it's not really an IR issue, if I'm wrong, please reopen it.
