### ISSUE TITLE
1.11.0 alpha 4 is incompatible with optifine G9

### ISSUE THREAD

**Issue by kann101** [GabrielOlvH/Industrial-Revolution#345]
IR 1.11.0 alpha 4 is incompatible with optifine G9.
The conflict was caused by MixinItemRenderer.class in the client directory in the mixin directory in the me directory in the IR 1.11.0 alpha 4.jar.

**Steps to Reproduce:**
It always happens when I try to use IR 1.11.0 alpha 4 and optifine_U_G9 at the same time.

However, this problem is easily solved.
If you delete MixinItemRenderer.class and delete the part that mentions MixinItemRenderer.class from indrev.mixins.json directly under IR 1.11.0 alpha 4.jar, optifine_U_G9 and IR 1.11. 0 alpha 4 can coexist.

**Comment by GabrielOlvH** [comment]
Thanks for reporting, however deleting classes isn't the way to go to fix these issues and Optifine compatibility isn't something I'm personally concerned about, there are other replacements for its features that don't break everything, and when they do we can actually do something about it since they are open sourced.
