### ISSUE TITLE
Miner veins not generating properly (1.6.6-BETA)

### ISSUE THREAD

**Issue by lenaclariel** [GabrielOlvH/Industrial-Revolution#36]
MC 1.16.2
indrev-1.6.6-BETA
fabric 0.9.3+build.207
fabric-api-0.20.1+build.401-1.16
(Ubuntu 18.04.5 LTS, which shouldn't be relevant but sometimes is)

Instead of generating the expected biome-specific veins, the scanner is **only returning veins of peat, lignite, and nikolite.** This occurs even in vanilla biomes, **including nether biomes** (where by rights none of those veins should spawn).

I encountered the issue in AoF3-2.0.2, but **replicated with just fabric-api, fabric-language-kotlin, and indrev** installed.

Having had a poke through the code, I believe the biome check is failing somehow (since, if I've read it correctly, it defaults to minecraft:ocean, and that would match the veins I listed).

**Comment by GabrielOlvH** [comment]
Thanks so much for this report, I had already found this issue and was about to rewrite the whole thing because I wasn't finding the main issue. With the 1.16.2 update, a lot of the way that biomes work have changed and I didn't notice that I had to change how I got the biome's information. I only noticed this after you mentioning it defaulting to Ocean. After this it was an easy fix and I'm able to find other veins normally now! The update may take a while to come out however because there are a lot of fixes/changes coming with them.
