### ISSUE TITLE
[REQUEST] Expand Farmers To Harvest/Grow Modded Crops

### ISSUE THREAD

**Issue by GalacticRuler** [GabrielOlvH/Industrial-Revolution#386]
**Description:**
- as the title implies, either expand the code on the backend to allow it to see more crop types, or add a datapack method of allowing crops manually

**Reason:**
- Currently you cannot automate farming of modded crops (Ex: Better Nether magma flowers and Feather ferns). This would be a life saver if added.

**Comment by GabrielOlvH** [comment]
Thank you for suggesting, but the Farmer does support modded crops. Apparently Better Nether reimplements Crops instead of using Vanilla's crop blocks, which is why the Farmer doesn't recognize it. 
Unless Better Nether switches to extending Minecraft's crop blocks, I would have to add explicit compat just for Better Nether which I won't because it's not really needed.
