### ISSUE TITLE
Revolutionary guide and veins

### ISSUE THREAD

**Issue by Karpathe** [GabrielOlvH/Industrial-Revolution#39]
Modpack: all of fabric 3
using the miner and chunk scanner, there seem to be new ore veins that are not in the book like wolframite.

**Comment by GabrielOlvH** [comment]
Some veins like Wolframite only exist alongside TechReborn which is why it doesn't show in the guide book. In the next update, you'll be able to right click scan reports and see every block that can be found there. Currently the only way of finding out what these extra veins have is check out [these files](https://github.com/GabrielOlvH/Industrial-Revolution/tree/master/src/main/resources/data/indrev/veintypes). Wolframite is tungsten, iron, pyrite and galena btw
