### ISSUE TITLE
[REQUEST] Compatibility with Applied Energistics 2

### ISSUE THREAD

**Issue by informatJonas** [GabrielOlvH/Industrial-Revolution#427]
**Description:**
- For all users of the mod "Applied Energistics 2" (AE2), it is certainly a pain to have to lay additional power cables to the "Fluix ME Glass Cable". With AE2, there is the possibility of using a "Quartz Fiber" cable to transfer ONLY power to a device. So you could build your system purely with the AE2 cables.

**Reason:**
- As described above, I would like to expect AE2 compatibility in Industrial Revolution. 
This not only simplifies cabling, but also saves resources in the end.

**Comment by Droseran** [comment]
You can currently send Industrial Revolution power over AE2 cables with the AE2 Energy P2P tunnels. This is one-to-many, so from a single input P2P tunnel you can supply IndRev power to multiple outputs. You still have to connect IndRev cables to and from the AE2 P2P tunnels and IndRev machines, but this allows you to have IndRev power anywhere your AE2 network goes.

**Comment by informatJonas** [comment]
I have now tried to connect an Electric Furnace with P2P ME Energy. However, the furnace does not receive any power.

**Comment by Droseran** [comment]
I had issues getting this to work at first too, so here are some notes I took while I was troubleshooting getting this setup to work:

- The P2P tunnels can be connected to either IndRev cable or an active side of an IndRev flux container.
- P2P tunnel is directional: energy can only flow from the input to the outputs, not the other way.
- The P2P tunnel that is copied to memory card becomes the input tunnel, any tunnel pasted is an output tunnel.
- Keep a copy of the memory card in a barrel next to the output tunnel so the tunnel can be moved easily.
- If the input tunnel is moved, the channel changes and must be re-copied to the memory card and pasted to the output tunnel.

To establish link:
1. Place IndRev flux container, set input and output side configurations
2. Place P2P input tunnel on flux container output side, or cable attached to output side
4. Right click the P2P tunnel with charged IndRev flux container to set as energy
5. Sneak, right click input P2P tunnel with memory card
6. Place output P2P tunnel at destination
7. Right click output P2P tunnel with charged flux container
8. Right click output P2P tunnel with memory card to link with input
9. Spend half an hour troubleshooting only to realize I put the tunnels on separate subnets
10. Move input tunnel to primary subnet instead of trunk subnet
11. Re-copy input tunnel to memory card and re-paste to output tunnel
12. Now it works

Hopefully some of this is helpful to you, it took me a few tries to get it working on my survival world after knowing it could work from a creative test world.

**Comment by informatJonas** [comment]
Thank you very much for your help.

Was about to send you my setup, when it suddenly worked after all

**Comment by 64-Tesseract** [comment]
I'd like to mention another problem on a similar note - IndRev can power AE2 systems via the Energy Acceptor, but cannot _take_ power from AE2. It's a bit annoying, since it's limiting me to storing all my power in the Flux Containers.

**Comment by Luligabi1** [comment]
@64-Tesseract That's the way intended by AE2 for the mod to be played, even its [wiki says so](https://appliedenergistics.github.io/features/me-network/network-energy):

> To power your network, you can either connect a Vibration Chamber directly, or use an Energy Acceptor to connect energy sources from compatible mods.

The best solution in your case is to connect your energy source to your flux containers and from there have a single cable power AE2 through a energy acceptor.

**Comment by 64-Tesseract** [comment]
Sure, but I don't see why it wouldn't be 2-directional...
It's not _that_ huge of an issue, just seems unintuitive to me

**Comment by Droseran** [comment]
There's a few reasons that I think they do it that way. 

The first is simple drama avoidance. There's been some issues in the past with mods having infinite loops and duplication of resources/energy when able to cycle back and forth. If I remember correctly, there was a massive blowup between two mod teams in the past over "imbalance" due how the two mods interacted when installed together, which led to one of the mod authors corrupting players' Minecraft worlds if their mod detected the other mod's existence. It's easier for AE2 to just avoid any potential issues by only accepting power to avoid similar circumstances.

Another reason is that they have complete control over their energy API this way. They can keep or break backwards compatibility when they need to. They can make the power/item flow as efficient (computationally) as possible without worrying about anything else crossing their network. They can update to new Minecraft/Fabric/etc. versions without waiting for external energy APIs before beginning.

The last, and possibly biggest reason when the mod started, is "realism." Applied Energistics 2 isn't based on a high-voltage power grid or factory design, it's meant to be a communications/low-voltage network. Think of the terminals, drives, crafting CPUs, etc. as PCs and servers, and the cables as ethernet lines/switches. The controllers are stacked/bridged network switches. The energy inputs are PSUs, and energy cubes are UPSes. This is the design that AE2 tries to build around. In real life networking, you can't send 120v/240v power over low-voltage data lines by regulation and simple physics (though you can send data over high-voltage with Ethernet over Power adapters, but let's ignore those.) It's meant to be the same with AE2, the mod is mimicking these types of networks, from channels being 8 and 32 port switches to calling the access stations terminals and requiring "CPUs" to manage the crafting flow.

I see their energy P2P terminals as a statement of, "Yes, we understand that this would be useful, and we agree, even though it slightly breaks our realistic design. Here's a way that works for both of us." The energy P2P terminals are metal conduit for the standard current lines to run near, but not directly with, the network cables.
